# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahaysite', '0002_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
